version: "2"
services:
  nginx:
    build: ./nginx
    links:
      - "node-app"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - adminnnet

  # Services
  node-app:
    command: sh -c './wait-for postgres:5432 -- node-start'
    depends_on:
      - postgres
    environment:
      JWT_PUBLIC_KEY: your-256-bit-secret
    build: ./app
    ports:
      - "9000:9000"
    volumes:
      - "./app:/app"
    networks:
      - adminnnet
  
  # Middleware
  postgres:
    build: ./db
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: postgres
    # logging:
    #   driver: none
    volumes:
      - ./pgdata/db:/var/lib/postgresql/data:delegated
    networks:
      - adminnnet
  
networks:
  adminnnet:
    driver: bridge
